const $ = id => document.getElementById(id);
let profileId = null;
function el(tag, text, className) { const node = document.createElement(tag); node.textContent = text; if (className) node.className = className; return node; }
async function api(path, options = {}) { const response = await fetch(path, options); const data = await response.json(); if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : JSON.stringify(data.detail)); return data; }
function jsonOptions(method, body) { return {method, headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)}; }
function showProfile(profile) { $('profile-status').textContent = profile.reviewed ? 'Profile confirmed. Click Find matches to see ranked jobs.' : 'PDF extracted. Review the fields below, then click Confirm corrected profile.'; profileId = profile.id; sessionStorage.setItem('jobmatch-profile', profileId); $('editor').hidden = false; for (const field of ['skills','experience','education']) $(field).value = [...new Set(profile[field].map(item => item.value))].join('\n'); $('source').textContent = profile.pages.map(page => `Page ${page.page}\n${page.text}`).join('\n\n'); }
async function action(button, operation) { button.disabled = true; try { await operation(); } catch (error) { $('status').textContent = error.message; $('profile-status').textContent = error.message; } finally { button.disabled = false; } }
$('upload').onclick = () => action($('upload'), async () => { if (profileId) throw new Error('Delete the current stored profile before importing a replacement.'); const file = $('pdf').files[0]; if (!file) throw new Error('Choose a PDF first.'); if (file.size > 10*1024*1024) throw new Error('PDF exceeds 10 MiB.'); $('profile-status').textContent = 'Extracting your PDF…'; showProfile(await api('/profiles',{method:'POST',headers:{'Content-Type':'application/pdf'},body:file})); $('status').textContent = 'Draft extracted. Correct all fields, then confirm the profile.'; });
$('save').onclick = () => action($('save'), async () => { const corrections = {}; for (const field of ['skills','experience','education']) corrections[field] = $(field).value.split('\n').map(v=>v.trim()).filter(Boolean); showProfile(await api(`/profiles/${profileId}`, jsonOptions('PUT',corrections))); $('status').textContent = 'Profile confirmed. Your edits are saved locally.'; });
$('delete').onclick = () => action($('delete'), async () => { await api(`/profiles/${profileId}`,{method:'DELETE'}); profileId = null; sessionStorage.removeItem('jobmatch-profile'); $('editor').hidden = true; $('source').textContent = ''; for (const field of ['skills','experience','education']) $(field).value = ''; $('pdf').value = ''; $('matches').replaceChildren(); $('count').textContent = 'Ready when you are'; $('status').textContent = 'Stored rÃ©sumÃ© and profile deleted. Your original file is unchanged.'; });
$('search').onclick = () => action($('search'), async () => { $('status').textContent = 'Searching… first model use may take time to download.'; const context = {}; if ($('years').value !== '') context.experience_years = Number($('years').value); if ($('locations').value.trim()) context.locations = $('locations').value.split(',').map(v=>v.trim()).filter(Boolean); if ($('mode').value) context.work_modes = [$('mode').value]; const data = await api('/search',jsonOptions('POST',{query:$('query').value,profile_id:profileId,approach:$('approach').value,context})); $('matches').replaceChildren(); $('count').textContent = `${data.results.length} matches`; $('status').textContent = data.score_notice; for (const row of data.results) renderMatch(row); });
function renderMatch(row) { const card = el('article','', 'match'); card.append(el('h3',row.job.title),el('p',`${row.job.location} · ${row.job.work_mode}`, 'meta'),el('p',`Ranking signal: ${row.score.toFixed(4)}`, 'score')); for (const conflict of row.assessment.conflicts) card.append(el('p',conflict.message,'conflict')); for (const kind of ['required','preferred']) { card.append(el('h4',`${kind === 'required' ? 'Required' : 'Preferred'} skills`)); const tags=el('div','','tags'); for (const item of row.assessment[kind]) tags.append(el('span',`${item.skill} · ${item.status.replace('_',' ')}`,`pill ${item.status}`)); card.append(tags); }
if (row.assessment.learning_priorities.length) {card.append(el('h4','Focused learning priorities')); const list=el('ul'); for (const item of row.assessment.learning_priorities) list.append(el('li',item.action)); card.append(list);}
const detail=el('details'); detail.append(el('summary','View source evidence')); for(const item of [...row.assessment.required,...row.assessment.preferred]) { detail.append(el('p',`${item.skill} · job quotation`),el('blockquote',item.evidence.quote)); for (const proof of item.resume_evidence || []) detail.append(el('blockquote',proof.evidence ? `Résumé page ${proof.evidence.page}: ${proof.evidence.quote}` : `User-confirmed statement: ${proof.value}`)); } detail.append(el('h4','Full job description'),el('p',row.job.description)); card.append(detail); $('matches').append(card); }
const previousId = sessionStorage.getItem('jobmatch-profile');
if (previousId) api(`/profiles/${previousId}`).then(showProfile).catch(() => sessionStorage.removeItem('jobmatch-profile'));
api('/health').then(health => {
  for (const option of $('approach').options) {
    if (health.search_modes[option.value] === false) {
      option.disabled = true;
      option.textContent += ' · setup required';
    }
  }
}).catch(() => { $('status').textContent = 'Unable to check search availability. Check the local server connection.'; });
